### ISSUE TITLE
can't find share function on rxjs

### ISSUE THREAD

**Issue by maxoon50** [FriOne/ng-io#1]
Hi, when i've got an error :  ERROR TypeError: __WEBPACK_IMPORTED_MODULE_2_rxjs_Observable__.a.create(...).share is not a function.

I saw in the source code that the share function is imported but maybe you can fix this issue? thanks

**Comment by FriOne** [comment]
@maxoon50 What version of rxjs are you using? Is it version 6?

**Comment by maxoon50** [comment]
no, it's version 5.5.6.
if i import directly RXJS/RX it works but it is not recommended as i see..

**Comment by FriOne** [comment]
@maxoon50 Try the last one, I remade the library with new CLI feature.
As far as I know rxjs 5 has pipe operator, so it should work fine.
Let me know if this doesn't work, have no time and project to test what I've done, sorry)

**Comment by maxoon50** [comment]
@FriOne it works fine, thanks a lot!
