### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by IdanCo** [FriOne/ng-io#2]
Thanks for the wonderful fork!

I got on error 
```
 Uncaught ReferenceError: global is not defined
    at Object../node_modules/ng-io/node_modules/socket.io-parser/is-buffer.js (is-buffer.js:4)
```

Fixed it by implementing this solution - https://github.com/socketio/socket.io-client/issues/1166#issuecomment-393592879

**Comment by FriOne** [comment]
Thanks! I will try to find some time to figure it out. Or, you could create a PR)
Not sure if it is necessary to put this variable into the library.
